### PR TITLE
Migrate from jsdom to parse5 + many improvements

### PR DESCRIPTION
**Pull request by perrin4869**
Still a lot of work to do, but I got around to fixing many problems and migrated from `jsdom` to `parse5` which is much better for this kind of problem actually. `parse5` for example contains a `TreeAdapter` class that allows for very elegant node type checking.

Run down of changes:
1. jsdom -> parse5
2. no longer starts pug output with a newline
3. cli.js was not executable, so doing `html2pug` didn't work because of lack of permissions
4. added an option called `fragment` which allows you to parse partial `html` documents, similar to the `bodyless` option in `html2jade`, only much more useful
5. comments with multiple lines will be converted to valid pug now
6. uses TreeAdapter to determine node types
7. no longer outputs pipelined texts if there is only one node... actually, right now because of the minifier, this is the only case anyways, not sure how to get it to preserve newlines between text nodes

No rush, enjoy the rest of your vacations!

### CODE REVIEW

**Comment by perrin4869** [comment]
@izolate any updates on this? This is the last PR I need to be able to migrate to `pug` in a clean manner hehe

**Comment by willycamargo** [comment]
@izolate ping

**Comment by perrin4869** [comment]
@izolate Any chance you get to review this in the near future?

**Comment by colinskow** [comment]
Might as well fork it, create your own NPM package and setup another website while you are at it.

**Comment by perrin4869** [comment]
@colinskow if you got a better idea I'm ready to hear it

**Comment by colinskow** [comment]
@perrin4869 I'm simply saying that since this project is not actively maintained and has several bugs such as #8, you might as well fork it and create your own NPM package since this is a useful tool.

**Comment by colinskow** [comment]
Or maybe @izolate is willing to give somebody else write access to this repository to keep in maintained.

**Comment by Rush** [comment]
@perrin4869 could you also remove commas from between attributes? Since quite a while they;'ve optional  in Jade/Pug.

**Comment by izolate** [comment]
Sorry for the neglect. I'm back now, new release is on the way...

**Pull request merged**
